#SPDX-License-Identifier: MIT
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    env_file: .env
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-password}
      GF_LOG_LEVEL: error
      DS_PROMETHEUS_AUGUR: Augur Postgres
      AUGUR_POSTGRES_PORT: ${AUGUR_DB_PORT:-5432}
      AUGUR_POSTGRES_DB: "${AUGUR_DATABASE:-augur}"
      AUGUR_POSTGRES_USER: "${AUGUR_DB_USER:-augur}"
      AUGUR_POSTGRES_PASS: "${AUGUR_DB_PASSWORD:-augur}"
    volumes:
      - ./gf_provisioning/dashboards:/etc/grafana/provisioning/dashboards:z
      - ./gf_provisioning/datasources:/etc/grafana/provisioning/datasources:z
    extra_hosts:
      - "host.containers.internal:host-gateway"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.containers.internal:host-gateway"

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    entrypoint: /bin/postgres_exporter --no-collector.wal
    env_file: .env
    environment:
      DATA_SOURCE_URI: "${AUGUR_DB_HOST:-host.containers.internal}:${AUGUR_DB_PORT:-5432}/${AUGUR_DATABASE:-augur}?sslmode=disable"
      DATA_SOURCE_USER: "${AUGUR_DB_USER:-augur}"
      DATA_SOURCE_PASS: "${AUGUR_DB_PASSWORD:-augur}"
    extra_hosts:
      - "host.containers.internal:host-gateway"

  prometheus-sql:
    image: ghcr.io/albertodonato/query-exporter:3.2.1
    # ports:
    #   - 9560:9560
    environment:
      AUGUR_DSN: "postgresql+psycopg2://${AUGUR_DB_USER:-augur}:${AUGUR_DB_PASSWORD:-augur}@${AUGUR_DB_HOST:-host.containers.internal}:${AUGUR_DB_PORT:-5432}/${AUGUR_DATABASE:-augur}?sslmode=disable"
    command:
      - --config
      - /etc/query-exporter/config.yaml
    volumes:
      - ./query-exporter:/etc/query-exporter:Z
    extra_hosts:
      - "host.containers.internal:host-gateway"

volumes:
  prometheus_data:
